#!/bin/bash

#skript mis lisab uue kasutaja või kasutajad talle etteantud failist koos#
#parooliga								 #

if [ $# -ne 1 ]; then
	echo "Vale sisend! Kasutusjuhend: $0 "kasutajanimi""
	exit
fi

failinimi=$1

if [ -f $failinimi -a -r $failinimi ]; then
	 echo "Fail on korras!"

 	 for nimi in $(cat $failinimi); do
	   kasutajanimi=$(echo "$nimi" | cut -f1 -d:)
           sh ./lisa_kasutaja $kasutajanimi
	   echo "$nimi" | chpasswd 
 	 done
else
   	 echo "probleem failiga $failinimi"
fi

